### ISSUE TITLE
Feature: Service Remoting

### ISSUE THREAD

**Issue by youyuanwu** [Azure/service-fabric-rs#3]
Add Service Remoting feature for Rust.
C# documentation: https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-services-communication-remoting

Add example of how to use service remoting.

**Comment by OscarTHZhang** [comment]
Is this related to Fabric Transport?

**Comment by youyuanwu** [comment]
FabricTransport was experimented in https://github.com/youyuanwu/fabric-rpc-rs
There service remoting is not planned to be supported.
